### ISSUE TITLE
Feature freeze

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/napari-micromanager#111]
I'd like to propose that we freeze feature development for a little bit (not including any existing PRs) and focus on cleaning everything up.  Let's get the number of PRs back down (preferably to zero).  Then work on refactoring the code, removing duplication, adding tests, speeding up tests, improving component isolation.  We've got a solid amount of functionality at this point, but things are starting to become less manageable.  It would be a good time to step back and do some cleanup.  

What do you think @fdrgsp @ianhi?

**Comment by ianhi** [comment]
Strong support!  

Should we even wait on merging existing PRs until refactoring? Although I can also see the argument for getting them all out of the way first.
