### ISSUE TITLE
Update for new pymmcore-plus mda interface 

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/napari-micromanager#130]
@ianhi, we need to update this repo now for https://github.com/pymmcore-plus/pymmcore-plus/issues/101

**Comment by ianhi** [comment]
Indeed. I actually got started on this but then it began morphing into a full overhaul of the mda widget. Maybe worth it to have a smaller part just updating the signals?

**Comment by tlambert03** [comment]
Yeah, a bare minimum compatibility pr would be good.  How does the widget need to change?

**Comment by ianhi** [comment]
I was hoping to make it more standalone like all the other PRs. It's also currently really coupled to the explore-sample widget (which actually handles the display) and some of it's logic lives on the main window rather than the widget

**Comment by tlambert03** [comment]
ah, yes.  That would be excellent

**Comment by tlambert03** [comment]
i'm not sure if there's anything actionable here anymore?  @ianhi?

**Comment by ianhi** [comment]
I believe all is well here
