### ISSUE TITLE
Move SequenceMETA in useq?

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/napari-micromanager#133]
As I'm trying to more loosely couple the mda widget with the rest of the app I'm running into an issue with the sequenceMeta

https://github.com/tlambert03/napari-micromanager/blob/50ef8f4abe8885331fc49a468d00ecb4cec86f0d/micromanager_gui/multid_widget.py#L21-L28

maybe this is something that should be part of useq-schema? Or we should just use the existing metadata field there?

**Comment by ianhi** [comment]
As a start see: https://github.com/tlambert03/useq-schema/pull/35

**Comment by tlambert03** [comment]
Yes, this was definitely something we imagined putting upstream.  We just put it here while we figured out what we might need.  I'll comment over on your PR

**Comment by ianhi** [comment]
Closed by https://github.com/pymmcore-plus/napari-micromanager/pull/224
