### ISSUE TITLE
Napari + Napari Micromanager plugin too large for my screen

### ISSUE THREAD

**Issue by CedricEsp** [pymmcore-plus/napari-micromanager#178]
Hello,

I have a small issue on a MacBook Pro (13inches), the napari-micromanager main window is too large for my screen, and unless I float the panel, I can't make the napari window smaller. Basically I don't have access to the bottom of the page:
<img width="1330" alt="Screen Shot 2022-06-21 at 7 54 22 PM" src="https://user-images.githubusercontent.com/85954420/174933471-804b8b4c-ff40-429a-bbaf-e50b42ea430a.png">
Not sure if there is something I could do on my side, outside accepting it :) 

Thanks!

**Comment by tlambert03** [comment]
Thanks @CedricEsp, I agree we generally need to make the main window more compact and adjustable.  Perhaps a workaround in the meantime: you can collapse the “stages” and “microscope” sections by clicking on their titles.  That should recover some space

**Comment by ianhi** [comment]
I suspect this is more about the horizontal space than the vertical. You can pop the plugin out into a standalone window using one of these buttons: 
![image](https://user-images.githubusercontent.com/10111092/175032351-5bdb59c0-a6a9-46f8-b8af-205390df37ca.png)
 which gives the horizontal space back to the image.

**Comment by fdrgsp** [comment]
closing. The new GUI has individual widget in the toolbar.
