### ISSUE TITLE
Stop "live acquisition"

### ISSUE THREAD

**Issue by CedricEsp** [pymmcore-plus/napari-micromanager#189]
Hello,

Quick question, I wonder if there is a "clean" way to stop the live acquisition programmatically? 
Doing `core.stopSequenceAcquisition(core.getCameraDevice())` does stop the sequence but doesn't toggle the `Live` button to `Stop` and I can't clear the preview layer in napari.

**Comment by ianhi** [comment]
Huh that's surprising, I would have suspected that this line would have made it all work: https://github.com/pymmcore-plus/napari-micromanager/blob/main/micromanager_gui/main_window.py#L90

Should be investigated, but as a workaround just call `main_window._stop_live()`

**Comment by fdrgsp** [comment]
I tested it again and this is solved in `pymmcore-widgets` `LiveButton`.
