### ISSUE TITLE
Stage start moving before stage up to load position

### ISSUE THREAD

**Issue by CedricEsp** [pymmcore-plus/napari-micromanager#190]
Hello,

When I move the stage from well to well I try to bring the focus device to the load position between the move but the stage start moving before the focus is done moving up, here the function I use:

```
def move_load_pos(core=None, XY=None):
    #Move stage to load position
    previous_z = core.getZPosition()
    core.setZPosition(0)
    core.waitForDevice(core.getFocusDevice())
    #Move to XY position
    core.setXYPosition(XY[0] ,XY[1])
    #Bring the stage back down
    core.waitForDevice(core.getXYStageDevice())
    core.setZPosition(previous_z)
    core.waitForDevice(core.getFocusDevice())
```

Do you see any reason for that to happens? I could definitely add some time delays.

Thanks for all your help!

**Comment by CedricEsp** [comment]
To go with that, when I run an engine with multiple position and z stack, the first z stack of every position is a little off, while if I add a `time.sleep(0.5)` before `self._mmc.snapImage()` it seems to fix  the issue.

**Comment by ianhi** [comment]
So in `prep_hardware` there is a `core.waitForSystem()` which is meant to block until the hardware is finished moving. If that's not happening then you may want to consider opening an issue on https://github.com/micro-manager/mmCoreAndDevices

**Comment by tlambert03** [comment]
@CedricEsp let us know if you need any more help here.  but I'll assume this is resolved for now

**Comment by CedricEsp** [comment]
Thanks @tlambert03, indeed the issue is with micromanager as suggested by @ianhi
