### ISSUE TITLE
Loading two differnet configs causes errors

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/napari-micromanager#250]
e.g. the demo config followed by real scope config will result in a crash

**Comment by fdrgsp** [comment]
I think this is not happening anymore. The only remaining issue (that does not prevent the correct loading of the cfg) is here in the `MMShuttersWidget` https://github.com/pymmcore-plus/napari-micromanager/blob/60f13ca27e04fe2d3fb83b9e6118a7db94da9a36/src/napari_micromanager/_gui_objects/_shutters_widget.py#L29-L37

I open a different issue for this #270 .
