### ISSUE TITLE
temp zarr file for MDA can overwhelm space on hard drive

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/napari-micromanager#251]
need to add a check!

**Comment by ianhi** [comment]
also, need to be able to clean up zarr arrays from finished MDAs if their layer gets closed

**Comment by tlambert03** [comment]
is this kind of a duplicate of #240?  If so, can you close one of them?  if not, can you clarify the difference?

**Comment by ianhi** [comment]
hmm i'm not sure why i opened this one in addition. Seems a strict duplicate
