### ISSUE TITLE
bug: mda widget broken on latest pymmcore-widgets

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/napari-micromanager#268]
The following lines are now out of date and throwing errors as the corresponding objects no longer exist in pymmcore-widgets

https://github.com/pymmcore-plus/napari-micromanager/blob/433cb9e0686ae837c934c66dfaba12b989c01106/src/napari_micromanager/_gui_objects/_mda_widget.py#L34-L44

n.b. you need to be running  https://github.com/pymmcore-plus/pymmcore-widgets/pull/159 in order to get far enough to run into these errors.

**Comment by tlambert03** [comment]
fixed with #269
