### ISSUE TITLE
Hardware autofocus implementation

### ISSUE THREAD

**Issue by GabeK-L** [pymmcore-plus/napari-micromanager#303]
Hi,

I have been testing napari-micromanager with Olympus IX81 microscopes. Are there any plans to add hardware autofocus into the MDA like there is in micromanager?

Thanks!

**Comment by tlambert03** [comment]
Hey @GabeK-L,
pymmcore-plus and useq-schema do support hardware autofocus, and the latest version of the MDA widget from pymmcore-widgets should have it in there... do you see something like this? (if not, update pymmcore-widgets)

<img width="640" alt="Screenshot 2024-01-11 at 1 24 06 PM" src="https://github.com/pymmcore-plus/napari-micromanager/assets/1609449/699ab009-7f1b-4251-9e3c-03c595d513e0">

the way to interpret those checkboxes is that hardware autofocus will be performed whenever the index of the corresponding axis changes.  So, for example, if you check the "p" box, autofocus will be performed each time you move to a new position, if you check "t", it will be performed at each time point, etc...

let me know how that goes for you

**Comment by tlambert03** [comment]
will also mention that most of our testing has been on Nikon PFS, so please do let us know if you run into any issues with the IX-81

**Comment by GabeK-L** [comment]
Awesome, thanks for the quick response. I will test it out and let you know if I have any issues.

**Comment by tlambert03** [comment]
I'm going to close this, but definitely do comment if you try it and have any issues
