### ISSUE TITLE
Create a tab for handling arbitrary config groups

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/napari-micromanager#44]
## Problem

Currently there is no way to modify a config group that is not special cased into the default UI (e.g. Channel). In contrast micromanager doesn't special case any of the config groups and instead devotes a large amount of UI real estate to changing the config groups:
![image](https://user-images.githubusercontent.com/10111092/131908193-9cd0d362-c993-4c2c-a11a-b3bc58bed38a.png)

## Proposed Solution

Either add a new tab to the bottom element (the arrow) or fill in the space (the box) with a config switching widget:
![image](https://user-images.githubusercontent.com/10111092/131908931-663cd30a-b1ef-4886-b130-7f2550e04afe.png)

**Comment by fdrgsp** [comment]
@ianhi I have also started working on the group/presets but for the same reason as in #78  I'm waiting to open a PR.

<img width="1440" alt="Screen Shot 2021-11-25 at 7 16 52 PM" src="https://user-images.githubusercontent.com/70725613/144126953-0e879074-d1e8-4dc3-916d-2e80a423610f.png">
<img width="1440" alt="Screen Shot 2021-11-25 at 7 17 30 PM" src="https://user-images.githubusercontent.com/70725613/144126949-8573a015-bb06-4586-9216-18b1313c5bd2.png">

**Comment by ianhi** [comment]
indeed it is!
