### ISSUE TITLE
Generalize (or hide) the autofocus up/down

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/napari-micromanager#78]
Currently there is a PFS-Offset control add by @fdrgsp in #68 

But this is specific to Nikon scopes, and not every scope will have autofocus. So this element should only be added if one is available (this is what MM does)

Or potentially there should be a dropdown for setting the Focus Device and we should only have a widget for the core focus device. 

Two other issues:
1. The up and down buttons are missing arrows
2. This only added a GUI element, but there doesn't seem to be any code/callbacks connected to it.
![image](https://user-images.githubusercontent.com/10111092/144117890-1fcf5e1d-ea87-441b-8476-93843ad29f99.png)

**Comment by fdrgsp** [comment]
@ianhi I did already continue developing the GUI in that direction but I wanted to close/merge the PR theta are currently open before opening a new PR (however the "PSF Offset" GUI elements is currently always there and not called only if there is an autofocus device). 

<img width="1440" alt="Screen Shot 2021-11-30 at 3 39 57 PM" src="https://user-images.githubusercontent.com/70725613/144124774-9dd8b17f-94c5-4c96-ba02-108385f07cea.png">

**Comment by tlambert03** [comment]
@ianhi @fdrgsp, please update status and/or close this

**Comment by fdrgsp** [comment]
not using this strategy anymore. closing.
