### ISSUE TITLE
pycro-manager backend

### ISSUE THREAD

**Issue by henrypinkard** [pymmcore-plus/napari-micromanager#97]
Hi @tlambert03, I wanted to let you know the changes we discussed before are now fully implemented and tested, and pycromanager can be used as a backend acquisition system with no GUI of its own.  If you continue adding features to this project, I think it would be awesome to integrate a pycromanager backend option, because 1) It would being a huge upgrade over the default pycromanager viewer. 2) It will eventually just work with the rest of Micro-Manager as well, since the pycromanager acquisition engine is slated to replace the Clojure engine running MDAs from the the micromanager GUI. 3) It would add in all the other nice features of pycromanager, like the flexible acquisition system, the[ lighting-fast data saving](https://pycro-manager.readthedocs.io/en/latest/performance_guide.html), and [opening enormous memory-mapped datasets in Napari with a few lines of code](https://pycro-manager.readthedocs.io/en/latest/read_data.html#opening-data-as-dask-array).

The way this works is through the combination of [headless mode](https://pycro-manager.readthedocs.io/en/latest/headless_mode.html), which allows you to launch the core and acquisition as a silent backend, and [saved image callbacks](https://pycro-manager.readthedocs.io/en/latest/image_saved_callbacks.html), which allows you to specify a function that gets called every time a new image is written to disk, so they it can be read directly in python. The idea is you can use these to update the viewer every time a new image arrives.

The current downsides of the pycromanager as a backend are that live mode and on-the-fly image processing are limited to 100MB/s (though they can be implemented much faster by saving to disk first and then reading). This is something I'm currently working on fixing.

Here is an example of how to use it:
```python
from pycromanager import Acquisition, multi_d_acquisition_events, start_headless

mm_app_path = '/path/to/micromanager'
config_file = mm_app_path + "/MMConfig_demo.cfg"

# Start the Java process
start_headless(mm_app_path, config_file, timeout=5000)

save_dir = r"C:\Users\henry\Desktop\data"

def image_saved_fn(axes, dataset):
    pixels = dataset.read_image(**axes)
    # TODO: use the pixels for something, like post-processing or a custom image viewer

with Acquisition(directory=save_dir, name="test", show_display=False,
                image_saved_fn=image_saved_fn,
                 ) as acq:
    events = multi_d_acquisition_events(
        num_time_points=5,
        z_start=0, z_end=6, z_step=0.4,
    )
    acq.acquire(events)
```

**Comment by tlambert03** [comment]
Hey @henrypinkard, would be great to have a swappable backend.  Is there a way to get callbacks from core for events outside of saved images?  That's something we probably need now too.  We should also check if the conversion between useq.MDASequence to your event dict is still working

**Comment by henrypinkard** [comment]
Yeah, I think I would just need to create something similar to [this class](https://github.com/henrypinkard/micro-manager/blob/master/mmstudio/src/main/java/org/micromanager/events/internal/CoreEventCallback.java) into pycromanager-java, and make a corresponding wrapper object on the python side. Should be easy enough.

Should I use `psygnal` for this? I see that its "Qt-style", but that doesn't mean it has dependencies on Qt, right? I would want to make this UI-agnostic.

I think the useq.MDASequence should work fine--I havent changed anything about events in a while

**Comment by tlambert03** [comment]
Yeah use psygnal.  Correct, no qt.  Pure python/cython event system

**Comment by ianhi** [comment]
> Yeah use psygnal. Correct, no qt. Pure python/cython event system

I think we found that to avoid crashes when in callbacks we had to use qt signals instead of pysgnal when in napari-micromanager. That's why https://github.com/tlambert03/pymmcore-plus/blob/main/pymmcore_plus/client/callbacks/qcallback.py exists and I had to add the same when switching a threads model.

**Comment by ianhi** [comment]
Further discussion of the differences between pysygnal and QCallback here: https://github.com/tlambert03/pymmcore-plus/issues/17

**Comment by ianhi** [comment]
The other issue would be the usage of methods that got added to pymmcore-plus such as `setRelativeXYZ` and `getOrGuessChannelGroup`. Would pycromanager need to implement those?

**Comment by tlambert03** [comment]
> I think we found that to avoid crashes when in callbacks we had to use qt signals instead of pysgnal when in napari-micromanager.

is this even independent of pyro?  can't remember anymore

**Comment by tlambert03** [comment]
> The other issue would be the usage of methods that got added to pymmcore-plus such as setRelativeXYZ and getOrGuessChannelGroup. Would pycromanager need to implement those?

Yeah, it's unclear exactly how to handle that.  It might be that we just start with the MDA widget for now.  That is, any backend that accepts an MDASequence object, executes the experiment, and emits frame-ready signals, is compatible (I know @kasasxav is interested in doing this for imswitch as well).

There's always going to be some degree of "stuff" a fully-feature GUI is going to want that isn't directly provided by the backend (whether it be pymmcore, pycromanager, or imswitch), so not sure exactly where to draw those lines such that one can keep pushing on the front-end while still having some hope of working with multiple backends

**Comment by ianhi** [comment]
>  > I think we found that to avoid crashes when in callbacks we had to use qt signals instead of pysgnal when in napari-micromanager.
> 
> is this even independent of pyro? can't remember anymore

unfortunately yeah. I ran into this in https://github.com/tlambert03/pymmcore-plus/pull/73 and had to add an optional qcallback on the non-pyro core.

**Comment by henrypinkard** [comment]
> The other issue would be the usage of methods that got added to pymmcore-plus such as `setRelativeXYZ` and `getOrGuessChannelGroup`. Would pycromanager need to implement those?

No I don't think so. One of the nice features of pycromanager from a maintenance/future proofing standpoint is that it discovers the core api dynamically at runtime. So no need to ever update it when the core changes. As such its probably best to avoid building on top of a potentially shifting API. (Though the callbacks would be the one exception to this rule...I don't see an easy way to avoid this).

It probably would make sense to just add these to the core directly if they were to be implemented in multiple wrappers.

**Comment by henrypinkard** [comment]
> It might be that we just start with the MDA widget for now. That is, any backend that accepts an MDASequence object, executes the experiment, and emits frame-ready signals, is compatible (I know @kasasxav is interested in doing this for imswitch as well).
> 
> There's always going to be some degree of "stuff" a fully-feature GUI is going to want that isn't directly provided by the backend (whether it be pymmcore, pycromanager, or imswitch), so not sure exactly where to draw those lines such that one can keep pushing on the front-end while still having some hope of working with multiple backends

For pycromanager in particular, the goal is to eventually shift away entirely from a particular model of a microscope and make this user configurable. For example, not assuming the "typical" one camera, one z stage, channels, etc. setup.  So in the ideal future it won't propagate specifications of how the microscope needs to be set up, what controls, etc. onto this library, and you can just freely design whatever you think is most useful, and have useq.MDASequence or something similar do the necessary translation

**Comment by ianhi** [comment]
> > The other issue would be the usage of methods that got added to pymmcore-plus such as setRelativeXYZ and getOrGuessChannelGroup. Would pycromanager need to implement those?
> 
> No I don't think so. One of the nice features of pycromanager from a maintenance/future proofing standpoint is that it discovers the core api dynamically at runtime.

sorry i meant need to in the sense that napari-micromanager depnds on those methods already. So switching to a backend without them would break things here. e.g. https://github.com/tlambert03/napari-micromanager/blob/db0e98bc53e293e826fc3e82473c9e210fbbccaa/micromanager_gui/main_window.py#L185

**Comment by henrypinkard** [comment]
That makes sense. I think this is something that would need to be implemented on your end though, since there isn't an explicit wrapping layer around the core in pycromanager analogous to pymmcoreplus, and I dont think it is a good idea to create one for the reason mentioned above. 

Any reason you couldn't just lift that method from pymmcoreplus into this library?

**Comment by tlambert03** [comment]
>since there isn't an explicit wrapping layer around the core in pycromanager analogous to pymmcoreplus, and I dont think it is a good idea to create one for the reason mentioned above.

pymmcore plus is a _very_ thin wrapper, providing primarily three, mostly independent things: 1) a more flexible signaling system and 2) interprocess communication and 3) a java/clojure-free mda engine.

While it's certainly an attractive idea to decouple from core completely (i.e. dynamic discovery at runtime), in reality the frequency of upstream changes is extremely minimal (less so those that require anything to change in pymmcore-plus).  So one has to weigh the cost/benefit of that abstraction.   pycromanager is itself addressing (2) and (3)  but does so in a way  that necessarily brings a third language and the Java runtime into the loop.  which has its own disadvantages.  Personally, that java dependence is the main reason that I've been looking for alternatives.  It's just not how I like to structure python projects if I can at all avoid it.  That said, I'm all for modular bits here; so inasmuch as there are alternate backends, each with their strengths, i think it well worth the effort to try to support them all!

I definitely agree that it's nice to make any and all scope config possible (i.e. we shouldn't tie it to one camera, one stage, etc)... but I leave that largely to micromanager, or whoever else (imswitch, etc) wants to implement it.  On the other hand, there is a _huge_ benefit for the vast majority of users who _do_ have relatively standard systems in starting with the most common use case and building a gui for it.  Generally speaking, I think it's important to make the common things easy, and the hard things possible...  (but starting with making common things easy is very practical)

**Comment by henrypinkard** [comment]
> 1) a more flexible signaling system

Just that signalling class or is there more?

> While it's certainly an attractive idea to decouple from core completely (i.e. dynamic discovery at runtime), in reality the frequency of upstream changes is extremely minimal (less so those that require anything to change in pymmcore-plus).

Recently, yes. Though [big changes may be coming soon](https://github.com/micro-manager/futureMMCore).

> pycromanager is itself addressing (2) and (3) but does so in a way that necessarily brings a third language and the Java runtime into the loop. which has its own disadvantages. Personally, that java dependence is the main reason that I've been looking for alternatives. It's just not how I like to structure python projects if I can at all avoid it.

I understand this, and in most cases I would agree. However, I think in this case an exception is warranted. One of the fundamental design principles of micro-manger, and a big part of how it has developed into such a useful tool, is that it encourages all users to work on the same interoperable code base. With all the possible combinations of hardware, it has an enourmous number permutations for use cases and thus relies heavily on user feedback and testing to improve and become more robust. The more consolidated this can be through common components, the more robust and powerful the whole software will be. We want to make efforts whenever possible to avoid fracturing layers of the software into different versions that do the exact same thing--imagine what a headache it would be if there were different versions of the core that worked with different devices

When @nicost and I were brainstorming the new acquisition engine that is now wrapped by pycromanager, we thought it was really important to avoid fracturing the larger micro-manager community into a Java only and Python only branches. Creating it in Java seemed like the only reasonable way to achieve this. Though it would be nice to have it in C, this would have required a huge amount of work to rewrite many other components from scratch. And I though I will always try to use Python when possible, there didn't seem to be any reasonable way to integrate this with the existing Java code base of the GUI.

Lastly, having some Java components behind the scenes doesn't create all that much complication from a user perspective because:
- The binaries for the Java Virtual Machine already come bundled with the MM installer (on windows, and mac in the [future](https://github.com/micro-manager/micro-manager/issues/1402)), so no additional installation required
- The JVM is quite mature and robust, is very portable across different OS's, and very rarely needs to be updated to new versions
- The Java-ness can be abstracted away for Python-only users. It's only internal components and you'll never have to touch a line of Java code (still some work to do, but moving in the right direction)
- The JVM is written in C++, so really its just one big C++ dependency anyway :)


> That said, I'm all for modular bits here; so inasmuch as there are alternate backends, each with their strengths, i think it well worth the effort to try to support them all!

Great! Me too

> I definitely agree that it's nice to make any and all scope config possible (i.e. we shouldn't tie it to one camera, one stage, etc)... but I leave that largely to micromanager, or whoever else (imswitch, etc) wants to implement it. On the other hand, there is a _huge_ benefit for the vast majority of users who _do_ have relatively standard systems in starting with the most common use case and building a gui for it. Generally speaking, I think it's important to make the common things easy, and the hard things possible... (but starting with making common things easy is very practical)

Well said, and I couldn't agree more. I think you have a much better sense than I of what the most common use cases are, and I'm always open to feedback on how to make them easier

**Comment by henrypinkard** [comment]
Back to the issue at hand: I added core callbacks to the new version of pycromanager/new MM nightly build. Since pycro-manager doesn't use any events/signalling, in order to keep the API consistent I added a callback function interface. By incorporating this code, you should be able to translate that into the signals you're looking for:


```python
from pycromanager import CoreCallback
from psygnal import Signal

class CMMCoreSignaler(CoreCallback):

    # native MMCore callback events
    propertiesChanged = Signal()
    propertyChanged = Signal(str, str, str)
    channelGroupChanged = Signal(str)
    configGroupChanged = Signal(str, str)
    configSet = Signal(str, str)
    systemConfigurationLoaded = Signal()
    pixelSizeChanged = Signal(float)
    pixelSizeAffineChanged = Signal(float, float, float, float, float, float)
    stagePositionChanged = Signal(str, float)
    XYStagePositionChanged = Signal(str, float, float)
    exposureChanged = Signal(str, float)
    SLMExposureChanged = Signal(str, float)


signaller = CMMCoreSignaler()
signaller.callback_fn = lambda name, *args: getattr(signaller, name, args)

# when youre done
signaller.close()

```

**Comment by tlambert03** [comment]
> Just that signalling class or is there more?

yes, it's just that, but the difference between that and the builtin events system is that `mmcore.registerCallback` doesn't make it very easy for an end-user to add additional callbacks (with something like `event.connect(callback)`).  You need to essentially rebuild a new callback object and register it over the previous one.  So when I say flexible, I'm referring more to the way that callbacks and collected and called (more on the psygnal or Qt side of things there, depending on which events you're using)

**Comment by tlambert03** [comment]
regarding the dependency on java, i think it's pretty easy to see both sides here right?  I acknowledge that it's not "that hard"... I can see that you're very comfortable with it.  My opinions come from other projects (such as wrapping bioformats for the aicsimageio library ... a good case where using java was really critical if we didn't want to reinvent decades of code).  And even with `conda install -c openjdk`, I still find some newcomers have difficulty with it.  I just think there's plenty of space for reasonable disagreement here on the merits/demerits of depending on the java runtime when technically, we don't need to

**Comment by henrypinkard** [comment]
Yes, you're right. And both are excellent points. And I would add that one can always make the case that experimenting with new approaches is valuable for its own sake. I think we can agree to disagree on this, and agree to agree on trying to make things modular and interoperable?

**Comment by nicost** [comment]
In the ideal world all universally useful code (in this case, acquisition engine, file saving, probably some more entities) would be in a layer with a C interface so that it can be used from any other environment without issues.  I like that idea very much, but the question is how much work is involved, and which of these things can we actually pull off in a reasonable amount of time.  Would love some face to face discussion about that (will send emails, but if anyone is following this and would like to be invited, please email me directly).

**Comment by tlambert03** [comment]
> but the question is how much work is involved, and which of these things can we actually pull off in a reasonable amount of time.

Totally agree.  After looking through the actual engine code, I felt that it was relatively straightforward enough to implement in python as well while we wait.  This is of course the most "sticky" point of all this.  But it's also why I think having an abstract spec for what an engine is even responsible for (ie useq schema) is also an important part of the puzzle.

**Comment by henrypinkard** [comment]
I guess I'd pictured this as more of me making changes on my side, you making changes on your side, but if you don't have interest/bandwidth for that, let's just forget about it

**Comment by ianhi** [comment]
Looked into a bit more and that adding signals and `getOrGuessChannelGroup` would get almost everything to work. The only thing that wouldn't would be the MDA panel which would take a bit more work.

**Comment by henrypinkard** [comment]
Sorry for the misunderstanding--good to hear!


> As I see it there are two main changes to pycromanager:
> 
>     1. The above mentioned signalling system
> 
>     2. Adding a few convenience methods (that would probably also benefit pycromanager users but are more complex to implement in C++) such as [`getOrGuessChannelGroup`](https://github.com/tlambert03/pymmcore-plus/blob/62416c797ec40a7c7614fc16061f1928ced8382d/pymmcore_plus/core/_mmcore_plus.py#L393)

These functionalities both live in pymmcore-plus, right? Would it be possible to add compatibility there with the pycromanager wrap of the java core? That and pymmcore would have nearly (or entirely) the same API I would think.

The reason I ask is because I think this might give you more freedom to experiment with changes going forard. I'm guessing that `getOrGuessChannelGroup` is just implemented using existing functions of the pymmcore--is that right? If so, and you want to add other functions like this in the future, with pycromanager's core were a backend, you could just freely do this and not have to worry about keeping pymmcore-plus and pycromanager in sync (or slogging around the c++ layer). 



> Then we could live in a crazy crazy world with both micromanager and napari-micromanager open side by side. which would be... well it'd be something :)

The future is now :)

![Screen Shot 2022-03-01 at 10 06 34 PM](https://user-images.githubusercontent.com/7969470/156304986-e85cfa3e-a1ea-46ab-9adf-db07fb977e00.png)

**Comment by ianhi** [comment]
> The reason I ask is because I think this might give you more freedom to experiment with changes going forard. 

Maybe this is a sign that we should hold on this for a little bit until the dust settles? Ultimately as I understand it the goal is to have pymmcore-plus be very stable and not so different from whats offered by the C++ core, but it's not quite been like that yet.

**Comment by henrypinkard** [comment]
> I thought about this, and it's appealing as an approach here but I couldn't figure out a nice way to do it :( I think the core of the issue is that it would involve inverting the python inheritance model a little bit. Because you need to first create an instance of the core, and then take an existing class with a parent and swap out that parent for this instance you have.

Could you just do it with `__new__`? In that method look at the args and see whether a pymmcore or a zmqcore is requested, and either construct the object or grab the existing instance. This does seem a little weird with the inheritance, but maybe python wouldn't care? Or if you removed the inheritance it would work I think--but maybe this leads to other problems with documentation etc? 

Something like this: https://github.com/micro-manager/pycro-manager/blob/c29269313671804e4a4003f4e9253fa6eff0170f/pycromanager/data.py#L329

> Maybe this is a sign that we should hold on this for a little bit until the dust settles? Ultimately as I understand it the goal is to have pymmcore-plus be very stable and not so different from whats offered by the C++ core, but it's not quite been like that yet.

I think its perfectly reasonable to want to have another layer around the the core that adds on some additional functionalities, and even if it were stable the alternative would still require an exact duplication of the methods in there in pycromanager, which makes the whole setup more work to maintain and more prone to errors. "Stability" is something that can be hard to achieve when you constantly come up with new ideas :)

**Comment by henrypinkard** [comment]
I've hidden the `Bridge` in the new version of pycromanager such that you just call:

```python
from pycromanager import Core

core = Core()
```

I believe if you do something like

```python
def __new__(cls, pm_backend=True, *args, **kwargs):
    if pm_backend:
       return Core()
    else:
       return PyMMCore...
```

You should be able to get what you need

**Comment by ianhi** [comment]
So I don't lose track of it. In https://github.com/tlambert03/pymmcore-plus/pull/102#issuecomment-1059604935 I have a proposal for a bridge package that makes a mixin class that could optionally be imported by napari-micromanager depending on what backend you want to use.
